gui:
  sidePanelWidtth: 0.2
  showNumstatInFilesView: true
  expandFocusedSidePanel: true
git:
  diffRenderers:
    - colorArg: always
      command: delta --light --paging=never --true-color always --line-numbers
